name: CMake

on:
  push:
    branches: [ master ]
    paths: [ ".github/workflows/build.yml", CMakeLists.txt, 'src/**', 'd2mapapi/**', 'tools/**', 'inih/**' ]
  pull_request:
    branches: [ master ]
    paths: [ ".github/workflows/build.yml", CMakeLists.txt, 'src/**', 'd2mapapi/**', 'tools/**', 'inih/**' ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        compiler: ["msys2_mingw", "msvc2022"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: CMake Configure and Build
        shell: cmd
        working-directory: ${{github.workspace}}
        run: "build_${{matrix.compiler}}.bat"

      - uses: actions/upload-artifact@v2
        with:
          name: D2RMH-snapshot-${{matrix.compiler}}
          path: |
            ${{github.workspace}}/build/${{matrix.compiler}}/dist/D2RMH-snapshot.zip
          retention-days: 7